name: elf
version: '0.31'
synopsis: An Elf parser
description: Parser for ELF object format
category: Data
author: Erik Charlebois
maintainer: aleksey.makarov@gmail.com
copyright: Erik Charlebois
license: BSD3
homepage: https://github.com/aleksey-makarov/elf
dependencies:
- base >=4.6 && <5.0
# extra-source-files:
# - testdata/tiny.elf
# - testdata/bloated.elf
# - testdata/vdso.elf
# - testdata/HOWTO
# - testdata/bloated.cpp
# - testdata/tiny.asm
tested-with: GHC == 8.6.2, GHC == 8.4.4, GHC == 8.2.2, GHC == 8.0.2
ghc-options: -Wall -Wcompat -Wincomplete-record-updates -Wincomplete-uni-patterns -Wno-redundant-constraints

github: aleksey-makarov/elf

library:
  dependencies:
    - base >= 2 && < 5
    - bytestring
    - binary
    - exceptions
    - intervals
    - lens
    - prettyprinter
    - singletons
    - template-haskell
    - mtl
  source-dirs: src
  other-modules:
    - Data.Elf.TH
    - Data.Elf.Generated
  exposed-modules:
    - Data.Elf
    - Data.Elf.Headers
    - Data.Elf.Doc
    - Data.Elf.Exception

tests:
#  tests:
#    main: Spec.hs
#    source-dirs: tests
#    other-modules:
#      - Data.ElfSpec
#    dependencies:
#      - base
#      - binary
#      - bytestring
#      - hspec >= 2.4 && < 3
#      - containers >= 0.5.9.2
#      - elf
# golden:
#    main: Golden.hs
#    source-dirs: tests
#    other-modules:
#      - Paths_elf
#    dependencies:
#      - base
#      - binary
#      - bytestring
#      - directory
#      - elf
#      - filepath
#      - typed-process
#      - tasty
#      - tasty-golden
#      - tasty-hunit
  golden:
    main: Golden.hs
    source-dirs: tests
    other-modules:
      - Paths_elf
    dependencies:
      - base
      - binary
      - bytestring
      - directory
      - elf
      - exceptions
      - filepath
      - prettyprinter
      - singletons
      - typed-process
      - tasty
      - tasty-golden
      - tasty-hunit

# executables:
#   hobjdump:
#     main: hObjDump.hs
#     source-dirs: app
#     ghc-options: -O2 -fno-warn-unused-do-bind -threaded -rtsopts -with-rtsopts=-N
#     dependencies:
#       - elf
#       - binary
#       - bytestring
#       - prettyprinter
#   hobjlayout:
#     main: hObjLayout.hs
#     source-dirs: app
#     ghc-options: -O2 -fno-warn-unused-do-bind -threaded -rtsopts -with-rtsopts=-N
#     dependencies:
#       - elf
#       - binary
#       - intervals
